### ISSUE TITLE
Measure Radial Entropy Produces an Error

### ISSUE THREAD

**Issue by NasimJ** [CellProfiler/CellProfiler-plugins#100]
I was testing the MeasureRadialEntropy module and regardless of the number of bins or type of intensity measurement (mean/median/integrated) this error occurs:
<img width="425" alt="Error" src="https://user-images.githubusercontent.com/55710463/81983464-7200a500-9601-11ea-9bba-b01aa593f334.png">

**To reproduce:**
Here is the pipeline and an image:
[PipelineandImage.zip](https://github.com/CellProfiler/CellProfiler-plugins/files/4630769/PipelineandImage.zip)

OS: MacOS Mojave 10.14.6
CellProfiler Version: 3.1.9 (Downloaded from the website)

+ Documentation of this module needs improvement.

**Comment by ErinWeisbart** [comment]
I am closing this issue because it refers to a plugin that we are not currently maintaining.
