### ISSUE TITLE
CP3 -> CP4: Wiki: Upgrade_setting method dropped 'from_matlab' from it's signature

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler-plugins#109]
Hi Team!

I am currently updating my plugins for CP4 (https://github.com/BodenmillerGroup/ImcPluginsCP) and running into smaller issues, that are not yet covered in the Wiki (https://github.com/CellProfiler/CellProfiler-plugins/wiki/CellProfiler-3-to-4-migration-guide)

As other maintainers are likely running into similar issues, I would like to add them to the wiki but am not sure what the best way to add them.
Thus I added now a section "Upgrade_setting method dropped 'from_matlab' from it's signature" but would be glad if someone from the core team could check if what I wrote is accurate.

If it is fine, please close this issue.

**Comment by bethac07** [comment]
Looks great, thanks!
