### ISSUE TITLE
Register with Zenodo and generate releases

### ISSUE THREAD

**Issue by votti** [CellProfiler/CellProfiler-plugins#115]
Hi,

I think for reproducibility reasons it would be good if this repository would get a DOI, such that it can be properly referred to in papers.

I made very good experiences with Zenodo: https://guides.github.com/activities/citable-code/

The only thing this requires is to:
a) Register the repository
b) Generate a release

Every release then automatically it's own DOI that is citable and archived for eternity.

This will improve the reproducibility of analyses that use these plugins, as it allows to properly refer to the specific version used using the DOI.
To be explicity: DOI would be less to assign credit, but more to be more specific what was exactly used. The 'original' papers presenting the modules should still be cited in any case.

Best, Vito

**Comment by bethac07** [comment]
Link is set up, will now automatically push to Zenodo on release! Thanks.
