### ISSUE TITLE
Malformed image name (is reported as 'missing') when pipeline runs 'Transforms' plugin module

### ISSUE THREAD

**Issue by imoutsatsos** [CellProfiler/CellProfiler-plugins#118]
Using CellProfiler Windows v4.0.7 and latest [CellProfiler4_AutoConvert plugins.](https://github.com/CellProfiler/CellProfiler-plugins/tree/master/CellProfiler4_AutoConvert)

Trying to run a 'Transforms' pipeline step. The plugin module always fails with ValueError indicating missing image names. 

The 'missing' image names are in fact valid image names but prefixed with a double colon ('::PROBE' for example)
![image](https://user-images.githubusercontent.com/3408226/105094473-542dee80-5a72-11eb-9f53-01e2a7ad1f14.png)

When we examine the exported pipeline file, we indeed observe a double colon separating the Transforms module parameter key-value as follows:
![image](https://user-images.githubusercontent.com/3408226/105094777-c6063800-5a72-11eb-8241-559def265f0f.png)
Even if we manually correct the pipeline file (so that a single colon replaces the double ones) and reload it, it still results to the same error. 
Note that in the CellProfiler UI,  all modules of the pipeline are valid and checked green!

**Comment by bethac07** [comment]
Hi @imoutsatsos ;

Can you try with the new version? It seems the setting text for the settings in that module had a ":" at the end of each setting text, which I think is what was causing the issues.

**Comment by imoutsatsos** [comment]
Thank you @bethac07 ; You are exactly right! it works now!
