### ISSUE TITLE
EnhancedMeasureTexture Module loading fails with missing 'from_matlab' positional argument error

### ISSUE THREAD

**Issue by imoutsatsos** [CellProfiler/CellProfiler-plugins#134]
Created a simple pipeline with just  'LoadData' and 'EnhancedMeasureTexture' module. Export the pipeline and try to re-import. Loading fails with error
![image](https://user-images.githubusercontent.com/3408226/136456948-7a5c6187-a209-4449-8020-b742a6873c80.png)

**Comment by ErinWeisbart** [comment]
Fixed by #139
