### ISSUE TITLE
Cannot find my plugin in Other module category

### ISSUE THREAD

**Issue by TummyPan** [CellProfiler/CellProfiler-plugins#145]
Hello,

I am trying to test a plugin developed by my team for CellProfiler, however, I cannot find my plugin in Other module category after copying it into plugins category and restarting CP, other built-in modules are visible. I've tried both CP 4 and CP 3 versions on my MacBook (macOS 11.6.2) with the workaround, i.e. extracting zip file directly to Application folder. I remember the first time I opened CP, the default plugins directory is a folder I cannot find in Library folder, then I changed it to Download folder. I gave CF full disk access permission though. I've heard about the same issue with other users, would source installation be an option to solve it? Or, do I have to set the plugins directory in Library folder? 

Thank you in advance.

**Comment by bethac07** [comment]
Hi,

Is the plugin written for CellProfiler 3 or CellProfiler 4? The former uses Python 2 and the latter Python 3, so you definitely will not be able to use it in both versions (we have a [migration guide](https://github.com/CellProfiler/CellProfiler-plugins/wiki/CellProfiler-3-to-4-migration-guide) if you want to convert from a CellProfiler 3 pipeline to CellProfiler 4.

Also, is the module's category definitely supposed to be "other"? If it is ie an Image Processing module, that's where it will be.  Can you see it in the list of modules when you select "All" as the category?

In general, you shouldn't NEED to run from source, the only requirement is to set your plugins directory preference setting to the folder where the plugin is, then restart CellProfiler. In practice, though, if there IS an issue in loading it (perhaps it introduces a dependency that isn't present in the built version of CellProfiler), it is helpful to have a terminal to diagnose why it won't load, for which you need to either be running on Windows or in CellProfiler from source on Mac.

**Comment by TummyPan** [comment]
Hi Beth,

Thanks so much for your prompt reply. 

The plugin is written in Python 3 so I'll stick to CellProfiler 4 as you advised. 

This plugin is supposed to be used as a gateway to submit jobs to HPC clusters. For instance, CellProfiler is installed locally, after adding this plugin at the end of the pipeline, user will be able to submit the pipeline to cluster once clicking "Analyse Images" button. I've also searched all the plugins in the All module category, my plugin is not there though. I will try it in on a Windows machine in the next few days to see if it works well on Windows.
