### ISSUE TITLE
plugin added to module folder but doesn't see it in cellprofiler modules

### ISSUE THREAD

**Issue by MariamFa** [CellProfiler/CellProfiler-plugins#146]
Hi everyone, 

I added a plugin (transformfilters.py) first to plugins and then copied it also to modules folder of cellprofiler in applications, but when I restart cellprofiler, the module is not there. Also, configuring logging doesn't exist in cellprofiler help button. My cellprofiler is version 4.2.1. 

I also tried restarting the computer (macOs BigSur v. 11.4) and it still didn't help. 

This is my first time adding a plugin to cell profiler so excuse me if the information provided is not sufficient. 

Thanks,
Mariam

**Comment by ErinWeisbart** [comment]
Please see our recently updated Troubleshooting information https://plugins.cellprofiler.org/troubleshooting.html and installation information https://plugins.cellprofiler.org/using_plugins.html
