### ISSUE TITLE
Plugins with external dependencies CAN work with binary CP distributions

### ISSUE THREAD

**Issue by hinerm** [CellProfiler/CellProfiler-plugins#166]
We got plugin modules working with binary CP distributions.

To do so, any dependencies can be copied out of a conda environment's `lib/site-packages` into the top-level directory of the binary.

![image](https://user-images.githubusercontent.com/1123809/194662563-c2d2bcb5-1e10-429d-9c82-8af4c4b49fd1.png)

It would be great if we could automate this practice somehow and update the instructions!

**Comment by bethac07** [comment]
@hinerm Neat! Did you get this working on Mac too or just Windows? Either way, could be a huge help!

**Comment by hinerm** [comment]
@bethac07 I only tested on windows but I'm hopeful for mac

**Comment by ErinWeisbart** [comment]
Added to documentation in #193 #197
