### ISSUE TITLE
Add "Remove Edge Masks" functionality to RunCellpose plugin

### ISSUE THREAD

**Issue by jenna-tomkinson** [CellProfiler/CellProfiler-plugins#168]
As I was working with the RunCellpose plugin in CellProfiler, I noticed that there was a function missing that is normally available in the `IdentifyPrimaryObjects` and `IdentifySecondaryObjects` modules, which is to remove the objects that have pixels touching the edge of the image. 

Cellpose 2.0 does have this functionality, called [`remove_edge_masks`](https://cellpose.readthedocs.io/en/latest/api.html#cellpose.utils.remove_edge_masks), within their documentation. It would be nice to have this ability within the module to remove the cells on the edge when wanting to proceed with further analysis like feature extraction.

**Comment by lauracmurphy** [comment]
There’s an option in the FilterObjects module where you can filter using “Image or mask border” that does what you need.
