### ISSUE TITLE
classifypixelsunet - file signature not found

### ISSUE THREAD

**Issue by wynstep** [CellProfiler/CellProfiler-plugins#180]
Hello everyone, I hope you can help me in solving an issue with CP plugin

I modified the classifypixelsunet.py to be compatible with keras 2+. I have essentially replaced lines with keras.layers.merge.concatenate into keras.layers.concatenate.

Now I have another error saying:

model.load_weights(weights_filename)
OSError: Unable to open file (file signature not found)

I believe it could be something related to the plugin not able to download/retrieve the weight file?

Could anyone please help?
Many thanks

**Comment by ErinWeisbart** [comment]
We are closing issues related to ClassifyPixelsUNET as we are not currently supporting the module.
We suggest that users interested in this plugin try our currently supported RunCellpose module as we understand it works better.

(Without digging into this, if you are still interested in running this plugin on your own, perhaps #122 contains the file you need?)
