### ISSUE TITLE
RunCellpose enhancement: If detecting cells, ask for nuclei to establish parent/child relationships

### ISSUE THREAD

**Issue by braymp** [CellProfiler/CellProfiler-plugins#227]
If RunCellpose is used for nuclei and cell object detection, the resultant objects are not related in a parent/child 1:1 manner as those created using IdentifyPrimary and IdentifySecondary. If the nuclei image is requested, perhaps expose an additional option to input nuclei objects as well.
The plugin does have an option to use the DNA image to guide cell detection/segmentation, but this does not guarantee a parent/child relationship.

**Comment by ErinWeisbart** [comment]
This functionality is now handled by #242 with the creation of EnforceObjectsOneToOne plugin.
It is not specific to Cellpose, but will take the input of any two sets of objects and force a 1:1 relationship, creating a new Primary:Secondary relationship.
