### ISSUE TITLE
RunOmnipose - HTTP error

### ISSUE THREAD

**Issue by tsmith1711** [CellProfiler/CellProfiler-plugins#241]
Hello, I am new for reporting errors so please ask if clarification is needed. I made a pipeline on my local Macbook M1 pro that included the RunOmnipose module. When I went to scale up my pipeline on our cluster, I encountered an error. I attached a screenshot of the error and was wondering if you have encountered this before. Any troubleshooting tips/tricks would be greatly appreciated!

<img width="542" alt="Screenshot 2024-03-29 at 3 26 21 PM" src="https://github.com/CellProfiler/CellProfiler-plugins/assets/89868694/074e6906-0639-4a10-8932-70bdcdd3edf9">

**Comment by tsmith1711** [comment]
For more context, we are running CellProfiler using a singularity container.

**Comment by tsmith1711** [comment]
I figured it out - I needed to add the model name ("bact_phase") in the download_cellpose_models.py file. The entire path for the file I modified was:

CellProfiler-plugins/dockerfiles/RunCellpose/download_cellpose_models.py

**Comment by ErinWeisbart** [comment]
@tsmith1711 Thanks for sharing your solution!
