### ISSUE TITLE
RunCellPose plugin script leads to not adding a working module

### ISSUE THREAD

**Issue by MikeLippincott** [CellProfiler/CellProfiler-plugins#247]
I was having issues getting RunCellPose to work in an existing pipeline. Upon further investagation with @jenna-tomkinson we found that the `runcellpose.py` script in the `CellProfiler-plugins/active_plugins` directory seems to be the culprit.

We found that the pipeline runs with the `runcellpose.py` script from commit `7bfb39005da6717595b9349f320397b4e2ca50ba` but fails to load with the `runcellpose.py` script from the main branch at the time of opening this issue. Commit `f0e4db193c1fc82cc5bd81844cc2ce307e307442`.

I am attaching screen shots to show what we see on our end:

Example of a pipeline that works usually with RunCellPose that is no longer working:
![f0e4db193c1fc82cc5bd81844cc2ce307e307442](https://github.com/CellProfiler/CellProfiler-plugins/assets/58147848/9bc2cad1-de2f-4e7f-97d0-c9b31c896bcf)

Example of a pipeline that works usually with RunCellPose that is working:
![7bfb39005da6717595b9349f320397b4e2ca50ba](https://github.com/CellProfiler/CellProfiler-plugins/assets/58147848/002b936e-d6b2-4c9e-9c06-73d18efde3aa)

Thank you for your help and continuous support on CellProfiler and CellProfiler-plugins! :)

**Comment by jenna-tomkinson** [comment]
To provide some more context, this is using CellProfiler v4.2.6 installed from [a conda environment](https://github.com/WayScience/live_cell_timelapse_apoptosis/blob/main/python_env.yml).

**Comment by bethac07** [comment]
Sorry, syntax error, fixed now, please pull.

**Comment by MikeLippincott** [comment]
This fixed the module error! Thank you! :D
