### ISSUE TITLE
y.segmented = y_data unboundlocalerror: local variable 'y_data' referenced before assignment

### ISSUE THREAD

**Issue by Pvannd** [CellProfiler/CellProfiler-plugins#249]
Cellpose version 3.0.10 and cellprofiler 4.2.6. I can't get cellpose to run as a plug-in. It runs in the same environment fine. But I can't edit the runcellpose file to much with out cellprofiler not recognizing the file. Please help me im losing sleep trying to figure it out. Ive changed the workers and GPU memory share workers but nothing has fix the issue for it to run.
![31f21affe6bca626ae6720de44a7ccc61842e668_2_750x1000](https://github.com/CellProfiler/CellProfiler-plugins/assets/174470313/08e35016-6866-4cb5-843a-81daa7bff88f)
![452a56dcf75121f31a5c74ffb064563219ba00dc_2_1332x1000](https://github.com/CellProfiler/CellProfiler-plugins/assets/174470313/81a846f0-12d1-4e0d-a41f-f406c40205e9)
![3b0b8d3bf8fd5581ad09d4b17784f85546780f1d_2_750x1000](https://github.com/CellProfiler/CellProfiler-plugins/assets/174470313/a316ea0d-4dd8-4696-b949-0d6b3ed6b77b)
![31645f6b34adc9ced4abf115012c16e8a0d450bb_2_750x1000](https://github.com/CellProfiler/CellProfiler-plugins/assets/174470313/b94bd7d3-0a9d-4454-a64f-f166bca60d14)

**Comment by bethac07** [comment]
Hi,

RunCellpose is not currently set up to run Cellpose 3. Apologies!
