### ISSUE TITLE
Is the MedialAxis plugin now a canonical module in CellProfiler?

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/CellProfiler-plugins#29]
There is a medialaxis.py module in the [primary CP repo](https://github.com/CellProfiler/CellProfiler/blob/d5cdc2df794e8acd80f3aa583491a5697a643dca/cellprofiler/modules/medialaxis.py) that conflicts the the medialaxis.py plugin in this repository.

**Comment by mcquin** [comment]
MedialAxis should be removed from CellProfiler-plugins: https://github.com/CellProfiler/CellProfiler/issues/3222#issuecomment-333002475
