### ISSUE TITLE
MergeObjects will remove objects which are smaller than the Minimum object size.

### ISSUE THREAD

**Issue by derekthirstrup** [CellProfiler/CellProfiler-plugins#33]
The preferred behavior is to preserve the label for objects which are below the minimum object size and have no touching neighbors to merge.

![image](https://user-images.githubusercontent.com/20077409/34747952-39de4542-f54f-11e7-8117-2ca1ef540cdb.png)

**Comment by AetherUnbound** [comment]
I'll make this behavior optional - thanks @derekthirstrup!
