### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/CellProfiler-plugins#52]
The link at the top of https://github.com/CellProfiler/CellProfiler-plugins/wiki/Measure-Image-Focus
is broken.  Perhaps it was intended to be the generic CP-plugins page? https://github.com/CellProfiler/CellProfiler-plugins 
or maybe just self-referring?
@jhung0 

P.S. This DL-trained focus measure is cool - I want to test it!

**Comment by ctrueden** [comment]
That README used to exist, but was deleted (with no explanation) in 16942503af4168a5ef9d69e2c2968841667664e7. Perhaps @jhung0 can shed light on why, and/or where that text lives now?

**Comment by ErinWeisbart** [comment]
I am closing this issue because it refers to a plugin that we are not currently maintaining.
