### ISSUE TITLE
Update documentation to clarify that some plugins need a CellProfiler version installed from source

### ISSUE THREAD

**Issue by cells2numbers** [CellProfiler/CellProfiler-plugins#79]
Some CellProfiler plugins need additional libraries. For example, to use the UNet plugin with the Windows version, the CNTK  libraries need to be installed. 

For this, CellProfiler needs to be installed from source, because the Windows installer comes bundled with its own python version.

**Comment by ErinWeisbart** [comment]
Fixed by recent overhaul of documentation and installation approach.
See https://plugins.cellprofiler.org/ for more information
