### ISSUE TITLE
New version of cellprofiler is missing some modules used to be used in plugins

### ISSUE THREAD

**Issue by nickorka** [CellProfiler/CellProfiler-plugins#88]
There are no some modules anymore, like 
cellprofiler.cpimage
cellprofiler.cpmodule 
and so on

**Comment by bethac07** [comment]
These have just been renamed; `cpimage` is now `image`, `cpmodule` is now `module`, etc.  These plugins are typically user contributed, so we do not take on responsibility for keeping them up-to-date, but if you wanted to update one we'd certainly take a pull request!
