### ISSUE TITLE
Save16BitPNGs doesn't save anything out 

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/CellProfiler-plugins#93]
@niklasTR Have you run into this? MacOSX 10.14.6, CellProfiler built 3.1.9

**Comment by NiklasTR** [comment]
Hi @bethac07 - will look into it! It used to work fine for CP 3.1.9 on Ubuntu 16.4. I will try it on my local machine as well.

**Comment by ErinWeisbart** [comment]
I am closing this issue because it refers to a plugin that we are not currently maintaining.
